"""
ReportService — generates a PDF fairness audit report using ReportLab.
"""

import os
import uuid
from datetime import datetime
from typing import Dict, Any, Optional, Tuple

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

# Directory where PDFs are stored (created on first use)
_REPORT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "reports")
_report_registry: Dict[str, str] = {}  # report_id → file path


def _ensure_report_dir():
    os.makedirs(_REPORT_DIR, exist_ok=True)


class ReportService:
    def generate_pdf(self, request) -> Tuple[str, str]:
        """Build a PDF and return (report_id, absolute_path)."""
        _ensure_report_dir()

        report_id = str(uuid.uuid4())
        filename = f"fairsight_{report_id}.pdf"
        path = os.path.abspath(os.path.join(_REPORT_DIR, filename))

        doc = SimpleDocTemplate(
            path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = self._build_story(request, styles)
        doc.build(story)

        _report_registry[report_id] = path
        return report_id, path

    def get_report_path(self, report_id: str) -> Optional[str]:
        return _report_registry.get(report_id)

    # ------------------------------------------------------------------
    # Story builders
    # ------------------------------------------------------------------
    def _build_story(self, request, styles):
        accent = colors.HexColor("#5B4FE9")
        story = []

        # Title
        title_style = ParagraphStyle(
            "title", parent=styles["Title"],
            fontSize=24, textColor=accent, spaceAfter=4
        )
        story.append(Paragraph(request.title, title_style))
        story.append(Paragraph(
            f"Generated by {request.author} &nbsp;·&nbsp; {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["Normal"],
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=accent, spaceAfter=12))

        # Session info
        story.append(Paragraph("Session Information", styles["Heading2"]))
        story.append(Paragraph(f"<b>Session ID:</b> {request.session_id}", styles["Normal"]))
        story.append(Spacer(1, 0.4 * cm))

        # Audit results
        if request.audit_results:
            story += self._render_metrics(request.audit_results, styles, accent)

        # Notes
        if request.notes:
            story.append(Spacer(1, 0.4 * cm))
            story.append(Paragraph("Notes", styles["Heading2"]))
            story.append(Paragraph(request.notes, styles["Normal"]))

        # Footer note
        story.append(Spacer(1, 1 * cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Paragraph(
            "<i>FairSight — AI Fairness Auditing Tool. "
            "Results are for informational purposes and should be reviewed by a qualified practitioner.</i>",
            styles["Normal"],
        ))
        return story

    def _render_metrics(self, results: Dict[str, Any], styles, accent) -> list:
        story = []
        story.append(Paragraph("Fairness Metrics", styles["Heading2"]))

        metrics = results.get("metrics", {})
        assessment = results.get("fairness_assessment", "N/A")

        # Assessment badge
        badge_color = colors.green if "FAIR" in assessment else colors.red
        badge_style = ParagraphStyle(
            "badge", parent=styles["Normal"],
            textColor=badge_color, fontSize=12, spaceAfter=8
        )
        story.append(Paragraph(f"<b>{assessment}</b>", badge_style))

        # Metrics table
        table_data = [["Metric", "Value"]]
        for k, v in metrics.items():
            label = k.replace("_", " ").title()
            table_data.append([label, str(v)])

        tbl = Table(table_data, colWidths=[10 * cm, 5 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), accent),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(tbl)
        return story
